openapi: 3.0.0
info:
  version: 1.0.0
  title: comment
  description: 评论 API
servers:
  - url: 'http://localhost:8080/api/item'
paths:
  /{itemId}/comments:
    get:
      summary: '获取某个商品的评论列表'
      operationId: get-comment-commodityId
      tags:
        - comment
      parameters:
        - name: page
          in: query
          description: 页面大小
          schema:
            type: integer
            format: int32
        - name: page
          in: query
          description: 页码
          schema:
            type: integer
            format: int32
        - name: itemId
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: 'OK'
          content:
            application/json:
              schema:
                properties:
                  count:
                    type: integer
                    format: int32
                  page:
                    type: integer
                    format: int32
                  size:
                    type: integer
                    format: int32
                  comments:
                    title: array
                    items:
                      $ref: '#/components/schemas/comment'
        '400':
          description: 'Bad Request'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/badRequest'
        '404':
          description: 'Not Found'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/notFound'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: '添加商品评论'
      operationId: post-comment-userId-commodity
      tags:
        - comment
      parameters:
        - name: itemId
          in: path
          required: true
          schema:
            type: integer
            format: int32
      requestBody:
        content:
          application/json:
            schema:
              properties:
                userId:
                  type: integer
                  format: int32
                content:
                  type: string
                
      responses:
        '201':
          description: 'Created'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/comment' 
        '400':
          description: 'Bad Request'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/badRequest'
        '404':
          description: 'Not Found'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/notFound'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'              
  /{itemId}/comments/{commentId}:
    delete:
      summary: '删除某一条评论'
      operationId: delete-comment-commentId
      tags:
        - comment
      parameters:
        - name: itemId
          in: path
          required: true
          schema:
            type: integer
            format: int32
        - name: commentId
          in: path
          description: 要删除的评论 ID
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: 'OK'
        '400':
          description: Bad Request'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/badRequest'
        '404':
          description: 'Not Found'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/notFound'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    badRequest:
      title: Bad Request
      type: object
      properties:
        error:
          type: object
          properties:
            message:
              type: string
    notFound:
      title: Not Found
      type: object
      properties:
        error:
          type: object
          properties:
            message:
              type: string
    Error:
      type: object
      required:
        - message
      properties:
        error:
          type: object
          properties:
            message:
              type: string
    comment:
      type: object
      required:
        - id
        - userId
        - userNickname
        - userAvatar
        - created_at
        - updated_at
        - content
      properties:
        id:
          type: integer
          format: int32
        userId:
          type: integer
          format: int32
        userAvatar:
          type: string
        userNickname:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        content:
          type: string
