openapi: 3.0.0
info:
  version: 1.0.0
  title: inventory
  description: 库存 API
servers:
  - url: 'http://localhost:8080/api/inventory'
paths:
  /commodity:
    get:
      summary: '获取某一类别的某页（十个）商品'
      operationId: get-commodity-pagenum
      tags:
        - commodity
      parameters:
        - name: type
          in: query
          description: 查询的商品类型
          required: true
          schema:
            type: integer
            format: int32
        - name: pageNumber
          in: query
          description: 查询的页码
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: 'OK'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/commodity'
        '400':
          description: 'Bad Request'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/badRequest'
        '404':
          description: 'Not Found'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/notFound'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: '添加商品'
      operationId: post-commodity-commodityId
      tags:
        - commodity
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/postCommodity'
      responses:
        '201':
          description: 'Created'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/commodityDetail'
        '400':
          description: 'Bad Request'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/badRequest'
        '404':
          description: 'Not Found'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/notFound'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /commodity/count:
     get:
      summary: '获取某一类别的商品总数'
      operationId: get-commodity-count
      tags:
        - commodity
      parameters:
        - name: type
          in: query
          description: 查询的商品类型
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: 'OK'
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: integer
                    format: int32
        '400':
          description: 'Bad Request'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/badRequest'
        '404':
          description: 'Not Found'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/notFound'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /commodity/search:
    post:
      summary: '搜索商品'
      operationId: post-commodity-search
      tags:
        - search
      parameters:
        - name: pageNumber
          in: query
          description: 查询的页码
          required: true
          schema:
            type: integer
            format: int32
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                type: string
      responses:
        '200':
          description: 'OK'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/commodity'
        '400':
          description: 'Bad Request'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/badRequest'
        '404':
          description: 'Not Found'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/notFound'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /commodity/search/count:
    post:
      summary: '获取符合关键词的商品总数'
      operationId: post-commodity-search-count
      tags:
        - search
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                type: string
      responses:
        '200':
          description: 'OK'
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: integer
                    format: int32
        '400':
          description: 'Bad Request'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/badRequest'
        '404':
          description: 'Not Found'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/notFound'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /commodity/{commodityId}:
    get:
      summary: '获取某个商品详情'
      operationId: get-commodity-commodityId
      tags:
        - commodity
      parameters:
        - name: commodityId
          in: path
          description: 查询的商品 ID
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: 'OK'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/commodityDetail'
        '400':
          description: 'Bad Request'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/badRequest'
        '404':
          description: 'Not Found'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/notFound'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      summary: '删除一个商品'
      operationId: delete-commodity-commodityId
      tags:
        - commodity
      parameters:
        - name: userId
          in: query
          description: 当前用户的 ID
          required: true
          schema:
            type: integer
            format: int32
        - name: commodityId
          in: path
          description: 要删除的商品 ID
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: 'OK'
        '400':
          description: 'Bad Request'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/badRequest'
        '404':
          description: 'Not Found'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/notFound'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'  
    put:
      summary: '修改商品信息'
      operationId: put-commodity-commodityId
      tags:
        - commodity
      parameters:
        - name: userId
          in: query
          description: 当前用户的 ID
          required: true
          schema:
            type: integer
            format: int32
        - name: commodityId
          in: query
          description: 更改的商品的 ID
          required: true
          schema:
            type: integer
            format: int32
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/postCommodity'
      responses:
        '200':
          description: 'OK'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/commodityDetail'
        '400':
          description: 'Bad Request'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/badRequest'
        '404':
          description: 'Not Found '
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/notFound'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    badRequest:
      title: Bad Request
      type: object
      properties:
        error:
          type: object
          properties:
            message:
              type: string
    notFound:
      title: Not Found
      type: object
      properties:
        error:
          type: object
          properties:
            message:
              type: string
    Error:
      type: object
      required:
        - message
      properties:
        error:
          type: object
          properties:
            message:
              type: string
    commodity:
      type: object
      required:
        - commodityId
        - commodityInfo
      properties:
        commodityId:
          type: integer
          format: int32
        commodityInfo:
          $ref: '#/components/schemas/commodityInfo'
    commodityInfo:
      type: object
      required:
        - commodityName
        - commodityPrice
        - commodityColor
        - commodityImage
        - commoditySpecefication
        - commodityInvertory
        - commodityType
      properties:
        commodityName:
          type: string
        commodityPrice:
          type: integer
          format: int32
        commodityColor:
          type: string
        commodityImage:
          type: string
        commoditySpecefication:
          type: string
        commodityInvertory:
          type: integer
          format: int32
        commodityType:
          type: integer
          format: int32
    commodityDetail:
      type: object
      required:
        - commodity
        - introduction
      properties:
        commodity:
          $ref: '#/components/schemas/commodity'
        introduction:
          type: string
    postCommodity:
      type: object
      required:
        - commodityInfo
        - introduction
      properties:
        commodityInfo:
          $ref: '#/components/schemas/commodityInfo'
        introduction:
          type: string