openapi: 3.0.0
info:
  version: 1.0.0
  title: payment
  description: 支付 API
servers:
  - url: 'http://localhost:8080/api/payment'
paths:
  /purchase:
    post:
      summary: '购买商品（生成订单）'
      operationId: post-purchase-orderId
      tags:
        - payment
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/payment'
      responses:
        '201':
          description: 'Created'
        '400':
          description: 'Bad Request'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/badRequest'
        '404':
          description: 'Not Found'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/notFound'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /tokenCoin:
    get:
      summary: '获取用户的代币数'
      operationId: get-tokenCoin-userId
      tags:
        - coin
      parameters:
        - name: userId
          in: query
          description: 当前用户 ID
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: 'OK'
          content:
            application/json:
              schema:
                type: object
                properties:
                  userId:
                    type: integer
                    format: int32
                  tokenCoin:
                    type: integer
                    format: int32
        '400':
          description: 'Bad Request'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/badRequest'
        '404':
          description: 'Not Found'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/notFound'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    put:
      summary: '修改用户的代币数'
      operationId: put-tokenCoin-userId
      tags:
        - coin
      requestBody:
        content:
          application/json:
            schema:
              properties:
                userId:
                  type: integer
                  format: int32
                tokenCoin:
                  type: integer
                  format: int32
      responses:
        '200':
          description: 'OK'
          content:
            application/json:
              schema:
                type: object
                properties:
                  userId:
                    type: integer
                    format: int32
                  tokenCoin:
                    type: integer
                    format: int32
        '400':
          description: 'Bad Request'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/badRequest'
        '404':
          description: 'Not Found'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/notFound'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error' 
components:
  schemas:
    badRequest:
      title: Bad Request
      type: object
      properties:
        error:
          type: object
          properties:
            message:
              type: string
    notFound:
      title: Not Found
      type: object
      properties:
        error:
          type: object
          properties:
            message:
              type: string
    Error:
      type: object
      required:
        - message
      properties:
        error:
          type: object
          properties:
            message:
              type: string
    payment:
      type: object
      required:
        - userId
        - deliveryId
        - commodities
      properties:
        userId:
          type: integer
          format: int32
        deliveryId:
          type: integer
          format: int32
        commodities:
          type: array
          items:
            type: object
            properties:
              commodityId:
                type: integer
                format: int32
              count:
                type: integer
                format: int32
