openapi: 3.0.0
info:
  version: 1.0.0
  title: user
  description: 用户 API
servers:
  - url: 'http://localhost:8080/api/user'
paths:
  /login:
    post:
      summary: '用户登录， 获取token'
      operationId: post-login-email
      tags:
        - user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                  format: password
      responses:
        '200':
          description: 'OK - login successfully'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/loginSuccess' 
        '400':
          description: 'Bad Request'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/badRequest'
        '404':
          description: 'Not Found'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/notFound'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'      
  /register:
    post:
      summary: '用户注册'
      operationId: post-register-email
      tags:
        - user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
                nickname:
                  type: string
      responses:
        '200':
          description: 'OK - register successfully'
        '400':
          description: 'Bad Request'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/badRequest'
        '404':
          description: 'Not Found'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/notFound'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /:
    get:
      summary: '管理员获取所有用户信息'
      operationId: get-user
      tags:
        - user
      parameters:
        - name: page
          in: query
          description: 页数
          required: true
          schema:
            type: integer
            format: int32
        - name: size
          in: query
          description: 页面大小
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: 'OK'
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: integer
                    format: int32
                  page:
                    type: integer
                    format: int32
                  size:
                    type: integer
                    format: int32
                  users:
                    type: array
                    items:
                      $ref: '#/components/schemas/user'
        '400':
          description: 'Bad Request'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/badRequest'
        '404':
          description: 'Not Found'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/notFound'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'      
  /{userId}:
    get:
      summary: '获取当前登录用户信息'
      operationId: get-user-id
      tags:
        - user
      parameters:
        - name: userId
          in: path
          description: 当前用户的 ID
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: 'OK'
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/user'
        '400':
          description: 'Bad Request'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/badRequest'
        '404':
          description: 'Not Found'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/notFound'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'   
    put:
      summary: '修改用户信息'
      operationId: put-user-userId
      tags:
        - user
      parameters:
        - name: userId
          in: path
          description: 当前用户的 ID
          required: true
          schema:
            type: integer
            format: int32
      requestBody:
        content:
          application/json:
            schema:
              properties:
                email:
                  type: string
                  format: email
                avatar:
                  type: string
                nickname:
                  type: string
      responses:
        '200':
          description: 'OK'
          content:
            application/json:
              schema:
                type: object
                properties:            
                  user:
                    type: object
                    $ref: '#/components/schemas/user' 
        '400':
          description: 'Bad Request'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/badRequest'
        '404':
          description: 'Not Found '
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/notFound'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /user{userId}/password:
    put:
      summary: '修改密码'
      operationId: put-user-password-userId
      tags:
        - user
      parameters:
        - name: userId
          in: path
          description: 当前用户的 ID
          required: true
          schema:
            type: integer
            format: int32
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                password:
                  type: string
      responses:
        '200':
          description: 'OK'
        '400':
          description: 'Bad Request'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/badRequest'
        '404':
          description: 'Not Found '
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/notFound'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /{userId}/deliveryInfos:
    get:
      summary: '获取用户收货信息'
      operationId: get-user-delivery-userid
      tags:
        - delivery
      parameters:
        - name: page
          in: query
          description: 页数
          required: true
          schema:
            type: integer
            format: int32
        - name: size
          in: query
          description: 页面大小
          required: true
          schema:
            type: integer
            format: int32
        - name: userId
          in: path
          description: 当前用户的 ID
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: 'OK'
          content:
            application/json:
              schema:
                properties:
                  count:
                    type: integer
                    format: int32
                  page:
                    type: integer
                    format: int32
                  size:
                    type: integer
                    format: int32
                  deliveryInfos:
                    type: array
                    items:
                      $ref: '#/components/schemas/deliveryInfo'
        '400':
          description: 'Bad Request'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/badRequest'
        '404':
          description: 'Not Found'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/notFound'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'   
    post:
      summary: '新建收货信息'
      operationId: post-delivery-userId
      tags:
        - delivery
      parameters:
        - name: userId
          in: query
          description: 当前用户的 ID
          required: true
          schema:
            type: integer
            format: int32
      requestBody:
        content:
          application/json:
            schema:
              properties:
                name:
                  type: string
                address:
                  type: string
                phone:
                  type: string
      responses:
        '201':
          description: 'Created'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/deliveryInfo' 
        '400':
          description: 'Bad Request'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/badRequest'
        '404':
          description: 'Not Found'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/notFound'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'     
  /{userId}/deliveryInfos/{deliveryId}:
    put:
      summary: '修改用户收货信息'
      operationId: put-delivery-deliveryId
      tags:
        - delivery
      parameters:
        - name: userId
          in: query
          description: 当前用户的 ID
          required: true
          schema:
            type: integer
            format: int32
        - name: deliveryId
          in: path
          description: 用户收货信息的 ID
          required: true
          schema:
            type: integer
            format: int32
      requestBody:
        content:
          application/json:
            schema:
              properties:
                name:
                  type: string
                address:
                  type: string
                phone:
                  type: string
      responses:
        '200':
          description: 'OK'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/deliveryInfo' 
        '400':
          description: 'Bad Request'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/badRequest'
        '404':
          description: 'Not Found '
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/notFound'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      summary: '删除某一个收货信息'
      operationId: delete-delivery-deliveryId
      tags:
        - delivery
      parameters:
        - name: userId
          in: query
          description: 当前用户的 ID
          required: true
          schema:
            type: integer
            format: int32
        - name: deliveryId
          in: path
          description: 用户收货信息的 ID
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: 'OK'
        '400':
          description: Bad Request'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/badRequest'
        '404':
          description: 'Not Found'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/notFound'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    badRequest:
      title: Bad Request
      type: object
      properties:
        error:
          type: object
          properties:
            message:
              type: string
    notFound:
      title: Not Found
      type: object
      properties:
        error:
          type: object
          properties:
            message:
              type: string
    Error:
      type: object
      required:
        - message
      properties:
        error:
          type: object
          properties:
            message:
              type: string
    loginSuccess:
      type: object
      required:
        - token
        - user
      properties:
        token:
          type: string
        user:
          type: object
          properties:
            id:
              type: integer
              format: int32
            email:
              type: string
              format: email
    user:
      type: object
      required:
        - email
        - nickname
        - avatar
      properties:
        email:
          type: string
        nickname:
          type: string
        avatar:
          type: string
        isAdmin:
          type: boolean
          default: false
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
    deliveryInfo:
      type: object
      required:
        - id
        - name
        - phone
        - address
      properties:
        id:
          type: integer
          format:  int32
        name:
          type: string
        phone:
          type: string
        address:
          type: string
